@baseUrl=http://localhost:3005/api


POST http://localhost:3005/api/users/login 
Content-Type: application/json

{
    "email": "taskmanger1update@gmail.com", 
    "password": "taskmanager"
}

###
# @authToken = {{login.response.body.token}}

###

POST http://localhost:3005/api/users/logout 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU0NzYwNTgwZDNlZjc5MjlmMDBlZWMiLCJpYXQiOjE2ODM4ODUzMTgsImV4cCI6MTY4NDQ5MDExOH0.ydFv8hXzGUgiMfnAC46ZmvzfMyZWsmBJcDLukRZp8A0 

###



GET {{baseUrl}}/users
Authorization: Bearer {{$response.body.token}}


###

###

GET {{baseUrl}}/users/6254760580d3ef7929f00eec

###

POST http://localhost:3005/api/users
Authorization: Bearer
content-type: application/json 

{
    "name":"taskuser1", 
    "email":"taskmanager1@gmail.com", 
    "password":"taskmanager"

}

###

DELETE {{baseUrl}}/users/645b407aa61a581b838ab5da

###

PATCH  {{baseUrl}}/users/6254760580d3ef7929f00eec 
content-type: application/json

{
    "name":"Sarfaraz Hussain",
    "email":"taskmanger1update@gmail.com", 
    "password":"taskmanager"
}

###