### set the baseurl as an environment variable
@baseUrl=http://localhost:3005/api

POST {{baseUrl}}/users/login 
Content-Type: application/json

{
    "email": "taskmanger1update@gmail.com", 
    "password": "taskmanager"
}
### Set the token as an environment variable ###
@authToken = response.body.token

### Logout API ###

POST {{baseUrl}}/users/logout 
Authorization: Bearer {{authToken}} 

###



GET {{baseUrl}}/users
Authorization: Bearer {{$response.body.token}}


###

###

GET {{baseUrl}}/users/6254760580d3ef7929f00eec

###

POST http://localhost:3005/api/users
Authorization: Bearer
content-type: application/json 

{
    "name":"taskuser1", 
    "email":"taskmanager1@gmail.com", 
    "password":"taskmanager"

}

###

DELETE {{baseUrl}}/users/645b407aa61a581b838ab5da

###

PATCH  {{baseUrl}}/users/6254760580d3ef7929f00eec 
content-type: application/json

{
    "name":"Sarfaraz Hussain",
    "email":"taskmanger1update@gmail.com", 
    "password":"taskmanager"
}

###